name: Release Action

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Standart Checkout
        uses: actions/checkout@v3

      - name: Set Version Number
        run: |
          echo "VERSION_NUMBER=$(echo "${{ github.ref }}" | sed 's#refs/tags/v##')" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=calendaronline" >> $GITHUB_ENV
          echo "DOCKER_TAG=ghcr.io/dpmpc/calendaronline" >> $GITHUB_ENV
        shell: bash

      - name: Build Docker Image
        run: |
          cd web
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_TAG}}:latest
          docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_TAG}}:${{ env.VERSION_NUMBER }}
      
      - name: Push Docker Image
        run: |
          docker login -u $GITHUB_REPOSITORY_OWNER -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
          docker push -a ${{ env.DOCKER_TAG }}  