name: Release Action

permissions:
  contents: read
  packages: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Standart Checkout
        uses: actions/checkout@v6

      - name: Set Version Number
        run: |
          echo "VERSION_NUMBER=$(echo "${{ github.ref }}" | sed 's#refs/tags/v##')" >> $GITHUB_ENV
          echo "DOCKER_APP_TAG=ghcr.io/dpmpc/calendaronline" >> $GITHUB_ENV
          echo "DOCKER_NGINX_TAG=ghcr.io/dpmpc/calendaronline-nginx" >> $GITHUB_ENV
        shell: bash

      - name: Prepare static files for nginx
        run: |
          echo "${{ env.VERSION_NUMBER }}" > web/creator/templates/creator/version.html
          cd nginx
          mv ../web/creator/static .

      - name: Build Docker Nginx Image
        uses: docker/build-push-action@v7
        with:
          context: nginx
          push: true
          tags: ${{ env.DOCKER_NGINX_TAG}}:latest,${{ env.DOCKER_NGINX_TAG}}:${{ env.VERSION_NUMBER }}

      - name: Build Docker App Image
        uses: docker/build-push-action@v7
        with:
          context: web
          push: true
          tags: ${{ env.DOCKER_APP_TAG}}:latest,${{ env.DOCKER_APP_TAG}}:${{ env.VERSION_NUMBER }} 
